# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: George Strakhov's Creative Midwifery
email: george.strakhov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  George Strakhov's home on the internets. Some rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://georgestrakhov.com" # the base hostname & protocol for your site
twitter_username: georgestrakhov
github_username:  GeorgeStrakhov

# Build settings
markdown: kramdown
